# Build stage
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Install Air for hot reloading
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY air.toml ./

EXPOSE 8080

CMD ["air"]