// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ApplicationTypeEnum string

const (
	ApplicationTypeEnumMASTERS ApplicationTypeEnum = "MASTERS"
	ApplicationTypeEnumPHD     ApplicationTypeEnum = "PHD"
)

func (e *ApplicationTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationTypeEnum(s)
	case string:
		*e = ApplicationTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationTypeEnum: %T", src)
	}
	return nil
}

type NullApplicationTypeEnum struct {
	ApplicationTypeEnum ApplicationTypeEnum
	Valid               bool // Valid is true if ApplicationTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationTypeEnum), nil
}

type NotificationsTypeEnum string

const (
	NotificationsTypeEnumDEADLINE  NotificationsTypeEnum = "DEADLINE"
	NotificationsTypeEnumINTERVIEW NotificationsTypeEnum = "INTERVIEW"
)

func (e *NotificationsTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationsTypeEnum(s)
	case string:
		*e = NotificationsTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationsTypeEnum: %T", src)
	}
	return nil
}

type NullNotificationsTypeEnum struct {
	NotificationsTypeEnum NotificationsTypeEnum
	Valid                 bool // Valid is true if NotificationsTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationsTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationsTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationsTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationsTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationsTypeEnum), nil
}

type ReplyVibeEnum string

const (
	ReplyVibeEnumENTHUSIASTIC ReplyVibeEnum = "ENTHUSIASTIC"
	ReplyVibeEnumGENERIC      ReplyVibeEnum = "GENERIC"
)

func (e *ReplyVibeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReplyVibeEnum(s)
	case string:
		*e = ReplyVibeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ReplyVibeEnum: %T", src)
	}
	return nil
}

type NullReplyVibeEnum struct {
	ReplyVibeEnum ReplyVibeEnum
	Valid         bool // Valid is true if ReplyVibeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReplyVibeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ReplyVibeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReplyVibeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReplyVibeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReplyVibeEnum), nil
}

type UniversityApplicationStatusEnum string

const (
	UniversityApplicationStatusEnumNOTAPPLIED              UniversityApplicationStatusEnum = "NOT APPLIED"
	UniversityApplicationStatusEnumSKIPPED                 UniversityApplicationStatusEnum = "SKIPPED"
	UniversityApplicationStatusEnumINPROGRESS              UniversityApplicationStatusEnum = "IN PROGRESS"
	UniversityApplicationStatusEnumPENDINGFEE              UniversityApplicationStatusEnum = "PENDING FEE"
	UniversityApplicationStatusEnumAPPLIED                 UniversityApplicationStatusEnum = "APPLIED"
	UniversityApplicationStatusEnumREJECTED                UniversityApplicationStatusEnum = "REJECTED"
	UniversityApplicationStatusEnumACCEPTEDWITHFUND        UniversityApplicationStatusEnum = "ACCEPTED WITH FUND"
	UniversityApplicationStatusEnumACCEPTEDWITHOUTFULLFUND UniversityApplicationStatusEnum = "ACCEPTED WITHOUT FULL FUND"
)

func (e *UniversityApplicationStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UniversityApplicationStatusEnum(s)
	case string:
		*e = UniversityApplicationStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UniversityApplicationStatusEnum: %T", src)
	}
	return nil
}

type NullUniversityApplicationStatusEnum struct {
	UniversityApplicationStatusEnum UniversityApplicationStatusEnum
	Valid                           bool // Valid is true if UniversityApplicationStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUniversityApplicationStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UniversityApplicationStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UniversityApplicationStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUniversityApplicationStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UniversityApplicationStatusEnum), nil
}

type Faculty struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	Email            sql.NullString
	UniversityID     uuid.UUID
	Designation      string
	ResearchAreas    []string
	InterestedPapers []string
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Interview struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	FacultyID   uuid.UUID
	Date        sql.NullTime
	Time        sql.NullTime
	IsCompleted sql.NullBool
	Remarks     sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Mail struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	FacultyID            uuid.UUID
	IsMailed             sql.NullBool
	IsMailReplied        sql.NullBool
	ReplyVibe            NullReplyVibeEnum
	IsInterviewRequested sql.NullBool
	Remarks              sql.NullString
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type Notification struct {
	ID                uuid.UUID
	UserEmail         string
	NotificationType  NullNotificationsTypeEnum
	NotificationRefID uuid.NullUUID
	EventTime         time.Time
	NotifyTime        time.Time
	Message           string
}

type Recommender struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Email        string
	Designation  sql.NullString
	Institution  sql.NullString
	Relationship sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type RecommenderStatus struct {
	ID             uuid.UUID
	ApplicationID  uuid.UUID
	RecommenderID  uuid.UUID
	IsLorSubmitted bool
	UserID         uuid.UUID
}

type University struct {
	ID                           uuid.UUID
	UserID                       uuid.UUID
	Name                         string
	Website                      sql.NullString
	Location                     sql.NullString
	MainRanking                  sql.NullInt32
	SubjectRanking               sql.NullInt32
	ApplicationFee               sql.NullInt32
	ApplicationDeadline          sql.NullTime
	EarlyDeadline                sql.NullTime
	IsGreMust                    sql.NullBool
	IsGmatMust                   sql.NullBool
	LorCount                     sql.NullInt32
	IsOfficialTranscriptRequired sql.NullBool
	IsTranscriptNeedsEvaluation  sql.NullBool
	AcceptedEvaluations          []string
	Remarks                      sql.NullString
	CreatedAt                    sql.NullTime
	UpdatedAt                    sql.NullTime
}

type UniversityApplication struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	UniversityID           uuid.UUID
	ShortlistedFacultiesID []uuid.UUID
	RecommendersID         []uuid.UUID
	ApplicationType        NullApplicationTypeEnum
	ApplicationStatus      NullUniversityApplicationStatusEnum
	LanguageScoreSubmitted sql.NullBool
	GreSubmitted           sql.NullBool
	GmatSubmitted          sql.NullBool
	Remarks                sql.NullString
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Name      string
	Username  string
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
